@baseUrl = http://localhost:5220

### Get all books
GET {{baseUrl}}/api/books
Accept: application/json

### Create a book
POST {{baseUrl}}/api/books
Content-Type: application/json

{
  "title": "The Hobbit",
  "author": "J.R.R. Tolkien",
  "publicationDate": "1937-09-21"
}

### Create a book WITHOUT a title (should fail with 400)
POST {{baseUrl}}/api/books
Content-Type: application/json

{
  "author": "Nobody",
  "publicationDate": "2000-01-01"
}

### Update book 2 (fixes one of the broken books)
PUT {{baseUrl}}/api/books/2
Content-Type: application/json

{
  "title": "Pippi Longstocking",
  "author": "Astrid Lindgren",
  "publicationDate": "1945-11-26"
}

### Update a book that doesn't exist (should fail with 404)
PUT {{baseUrl}}/api/books/999
Content-Type: application/json

{
  "title": "Ghost book",
  "author": "Nobody",
  "publicationDate": "2000-01-01"
}

### Update with an EMPTY title (should fail with 400)
PUT {{baseUrl}}/api/books/2
Content-Type: application/json

{
  "title": "",
  "author": "Astrid Lindgren",
  "publicationDate": "1945-11-26"
}

### Delete book 3
DELETE {{baseUrl}}/api/books/3

### Delete book 4
DELETE {{baseUrl}}/api/books/4

### Delete a book that doesn't exist (should fail with 404)
DELETE {{baseUrl}}/api/books/999

### Register a user
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "Malin",
  "password": "abc"
}
